from app.services.gcode_parser import parse_gcode

ORCA_MULTI = """; generated by OrcaSlicer 1.9.0 on 2026-06-29
; filament_type = PLA;PETG;PLA;TPU
; filament_colour = #000000;#FF0000;#00FF00;#0000FF
; filament_diameter = 1.75,1.75,1.75,1.75
; filament_density = 1.24,1.27,1.24,1.21
T0
T1
M600
T2
T3
; filament used [mm] = 0, 1680.2, 2490.1, 13200.5
; filament used [g] = 0.00, 5.09, 7.54, 39.97
; estimated printing time (normal mode) = 1h 23m 45s
"""

PRUSA_SINGLE = """; generated by PrusaSlicer 2.7.1
; filament_type = PLA
; filament used [g] = 5.09
; estimated printing time (normal mode) = 10m
"""

CURA = """;FLAVOR:Marlin
;Generated with Cura_SteamEngine 5.6.0
;TIME:3600
;Filament used: 1.2m
"""


def test_orca_multi_tool_matches_tz_example():
    r = parse_gcode(ORCA_MULTI, "demo.gcode")
    assert r["slicer_name"] == "OrcaSlicer"
    assert r["tool_count"] == 4
    assert [t["used_g"] for t in r["tools"]] == [0.0, 5.09, 7.54, 39.97]
    assert r["total_filament_used_g"] == 52.6
    assert r["estimated_print_time_sec"] == 5025
    # материалы и плотности раскладываются по индексу инструмента
    assert r["tools"][3]["material"] == "TPU"
    assert r["tools"][1]["color_hex"] == "#FF0000"
    assert float(r["tools"][0]["density_g_cm3"]) == 1.24


def test_prusa_single_tool():
    r = parse_gcode(PRUSA_SINGLE, "one.gcode")
    assert r["slicer_name"] == "PrusaSlicer"
    assert r["tool_count"] == 1
    assert r["tools"][0]["used_g"] == 5.09
    assert r["estimated_print_time_sec"] == 600


def test_cura_time_in_seconds():
    r = parse_gcode(CURA, "c.gcode")
    assert r["slicer_name"] == "Cura"
    assert r["estimated_print_time_sec"] == 3600


def test_file_hash_is_stable():
    a = parse_gcode(b"; x = 1\n", "a.gcode")
    b = parse_gcode(b"; x = 1\n", "a.gcode")
    assert a["file_hash"] == b["file_hash"]
